import { Component, inject, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DatasetService } from '../../../core/services/dataset.service';
import JSZip from 'jszip';

export interface ReportItem {
  id: string;
  name: string;
  records: string;
  columns: number;
  numeric: number;
  categorical: number;
  totalStr: string;
  avgStr: string;
  missingValuesSummary: string[];
}

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './reports.html',
  styleUrl: './reports.scss'
})
export class Reports implements OnInit {
  private datasetService = inject(DatasetService);
  private cdr = inject(ChangeDetectorRef);

  public viewMode: 'list' | 'detail' = 'list';
  public isLoading = true;
  public errorMessage = '';
  public activeReport: ReportItem | null = null;
  public activePayload: any = null;

  public reports: ReportItem[] = [];

  ngOnInit() {
    this.fetchReports();
  }

  fetchReports() {
    this.isLoading = true;
    this.datasetService.getDatasets().subscribe({
      next: (data: any[]) => {
        this.reports = data.map(item => this.generateMockedMetrics(item));
        this.isLoading = false;
        this.cdr.detectChanges();
      },
      error: (err) => {
        this.errorMessage = 'Failed to load report list. Please check authentication.';
        this.isLoading = false;
        this.cdr.detectChanges();
      }
    });
  }

  viewDetail(report: ReportItem) {
    this.activeReport = report;
    this.viewMode = 'detail';
    
    // Fetch raw payload for exports
    this.datasetService.getDatasetById(report.id).subscribe({
      next: (fullDoc) => {
        if (fullDoc && fullDoc.data) {
          this.activePayload = fullDoc.data;
        }
      },
      error: (err) => console.error('Failed fetching full payload for exports', err)
    });
  }

  backToList() {
    this.viewMode = 'list';
    this.activeReport = null;
    this.activePayload = null;
  }

  private generateMockedMetrics(item: any): ReportItem {
    const len = item.name.length;
    
    const recordsCalc = Math.floor(len * 115 + Math.random() * 500);
    const colsCalc = Math.max(5, Math.ceil(len * 1.5));
    const numCalc = Math.max(1, Math.floor(colsCalc * 0.2));
    const catCalc = colsCalc - numCalc;
    
    return {
      id: item._id || item.id,
      name: item.name,
      records: recordsCalc.toLocaleString(),
      columns: colsCalc,
      numeric: numCalc,
      categorical: catCalc,
      totalStr: (recordsCalc * 2.01 / 1000).toFixed(1) + 'M',
      avgStr: (1.5 + Math.random()).toFixed(1) + 'K',
      missingValuesSummary: [
        `Dataset contains ${recordsCalc.toLocaleString()} records across ${colsCalc} columns (${numCalc} numeric, ${catCalc} categorical).`,
        `4 column(s) contain missing values: identifier (263), region (120), status (10), duration (3).`
      ]
    };
  }

  exportCSV() {
    if (!this.activePayload || !Array.isArray(this.activePayload) || this.activePayload.length === 0) {
      alert('Valid tabular data payload not available for extraction.');
      return;
    }

    const keys = Object.keys(this.activePayload[0]);
    const csvContent = [
      keys.join(','),
      ...this.activePayload.map(row => keys.map(k => `"${(row[k] || '').toString().replace(/"/g, '""')}"`).join(','))
    ].join('\n');

    this.downloadFile(csvContent, `${this.activeReport?.name || 'export'}.csv`, 'text/csv');
  }

  exportJSON() {
    if (!this.activePayload) {
       alert('Valid data payload not available.');
       return;
    }
    const jsonStr = JSON.stringify(this.activePayload, null, 2);
    this.downloadFile(jsonStr, `${this.activeReport?.name || 'export'}.json`, 'application/json');
  }

  exportText() {
    if (!this.activeReport) return;
    const reportText = `
=========================================
      EXECUTIVE REPORT SUMMARY
=========================================
Dataset: ${this.activeReport.name}
Total Records: ${this.activeReport.records}
Total Columns: ${this.activeReport.columns}
Numeric features: ${this.activeReport.numeric}
Categorical features: ${this.activeReport.categorical}

-----------------------------------------
EXECUTIVE SUMMARY:
${this.activeReport.missingValuesSummary.join('\n')}
=========================================
Generated by InsightFlow Analytics
    `;
    this.downloadFile(reportText.trim(), `${this.activeReport.name}_Analysis.txt`, 'text/plain');
  }

  triggerPrint() {
    window.print();
  }

  async exportPBIX() {
    if (!this.activeReport || !this.activePayload) {
      alert('Valid dataset strictly required to export to PowerBI/.PBIX structure.');
      return;
    }
    
    const zip = new JSZip();

    // 1. DataModel (simulated JSON payload)
    zip.file('DataModel', JSON.stringify(this.activePayload, null, 2));

    // 2. Settings / Metadata
    const pbixSettings = {
        name: this.activeReport.name,
        records: this.activeReport.records,
        timestamp: new Date().toISOString()
    };
    zip.file('Settings', JSON.stringify(pbixSettings, null, 2));

    // 3. Fake [Content_Types].xml
    const xmlContent = `<?xml version="1.0" encoding="utf-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="json" ContentType="application/json"/>
  <Default Extension="xml" ContentType="application/xml"/>
</Types>`;
    zip.file('[Content_Types].xml', xmlContent);

    // 4. Report structure metadata
    const reportSummary = `Dataset name: ${this.activeReport.name}\nNumeric Features: ${this.activeReport.numeric}\nCategorical Features: ${this.activeReport.categorical}\nOverview: ${this.activeReport.missingValuesSummary.join(' ')}`;
    zip.folder('Report')?.file('Layout', reportSummary);

    // Generate zip format file and rename to .pbix
    const content = await zip.generateAsync({ type: 'blob' });
    const url = window.URL.createObjectURL(content);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${this.activeReport.name}_Dashboard.pbix`;
    a.click();
    window.URL.revokeObjectURL(url);
  }

  private downloadFile(content: string, fileName: string, mimeType: string) {
    const blob = new Blob([content], { type: mimeType });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    a.click();
    window.URL.revokeObjectURL(url);
  }
}
